use_frameworks!

target 'HummAPI_Example' do
  pod 'AFNetworking', '~> 2.5'
  pod 'JSONModel'
  pod 'HummAPI', :path => '../'

end

target 'HummAPI_Tests' do
  pod 'HummAPI', :path => '../'
  pod 'AFNetworking', '~> 2.5'
  pod 'JSONModel'
  pod 'Specta'
  pod 'Expecta'
end
