use_frameworks!

target 'HummAPI_Example', :exclusive => true do
  pod 'HummAPI', :path => '../'
  pod 'AFNetworking', '~> 2.5'
  pod 'JSONModel'

end

target 'HummAPI_Tests', :exclusive => true do
  pod 'HummAPI', :path => '../'
  pod 'AFNetworking', '~> 2.5'
  pod 'JSONModel'
  pod 'Specta'
  pod 'Expecta'
end
