use_frameworks!

target 'HummAPI_Example', :exclusive => true do
  pod 'HummAPI', :path => '../'
end

target 'HummAPI_Tests', :exclusive => true do
  pod 'HummAPI', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
